#!/usr/bin/env python

import os, sys
import signal

stdin = os.fdopen(sys.stdin.fileno(), 'rb')
stdout = os.fdopen(sys.stdout.fileno(), 'wb')
total = 0
freq = 10

def progress(signum, frame):
    global total
    if total > -1:
        sys.stderr.write('--> Recv %i bytes\n' % total)
        sys.stderr.flush()
        signal.alarm(freq)

signal.signal(signal.SIGALRM, progress)
signal.alarm(freq)

try:
    for data in stdin.read():
        stdout.write(data)
        total = total + len(data)
except Exception as ex:
    sys.stderr.write('pipecount: {}: {}\n'.format(ex.__class__.__name__, ex))

sys.stderr.write('--> Recv %i total bytes\n' % total)
sys.stderr.flush()
total = -1

try:
    stdin.close()
except:
    pass

try:
    stdout.close()
except:
    pass

try:
    sys.stderr.close()
except:
    pass

sys.exit(1 if total == 0 else 0)
