#!/usr/bin/env python

import os, sys

stdin = os.fdopen(sys.stdin.fileno(), 'rb')
stdout = os.fdopen(sys.stdout.fileno(), 'wb')
total = 0

def progress(signum, frame):
    global total
    print('Sent %i bytes' % total)
    signal.alarm(30)

signal.signal(signal.SIGALRM, progress)
signal.alarm(30)

try:
    for data in stdin.read():
        stdout.write(data)
        total = total + len(data)
except Exception as ex:
    print('pipecount: {}: {}'.format(ex.__class__.__name__, ex))

signal.alarm(0)

try:
    stdin.close()
except:
    pass

try:
    stdout.close()
except:
    pass

sys.stderr.write('Sent %i total bytes' % total)

sys.exit(1 if total == 0 else 0)
