#!/usr/bin/env python

import os, sys

stdin = os.fdopen(sys.stdin.fileno(), 'rb')
stdout = os.fdopen(sys.stdout.fileno(), 'wb')
total = 0

try:
    for data in stdin.read():
        stdout.write(data)
        total = total + len(data)
except Exception as ex:
    print('pipecount: {}: {}'.format(ex.__class__.__name__, ex))

try:
    stdin.close()
except:
    pass

try:
    stdout.close()
except:
    pass

sys.exit(1 if total == 0 else 0)
